### ISSUE TITLE
How to emit `nonnull` as a parameter attribute?

### ISSUE THREAD

**Issue by justinclift** [llir/llvm#88] opened 2019-06-08 03:43 UTC
Came across an LLVM IR line that (so far) I've not been able to generate identically using `llir/llvm`:

```
tail call fastcc void %8(i8* nonnull %0), !dbg !33
```

The `nonnull` there doesn't seem to emit.  eg:

```
foo := ir.NewParam("", types.I8Ptr)
foo.Attrs = []ir.ParamAttribute{enum.ParamAttrNonNull}
someCall := ifThenIBlock.NewCall(val8, foo)  // val8() is already defined in earlier code
someCall.Tail = enum.TailTail
someCall.CallingConv = enum.CallingConvFast
someCall.Metadata = append(someCall.Metadata, &metadata.Attachment{Name: "dbg", Node: dbgLoc["33"]})
```

Sill emits:

```
tail call fastcc void %8(i8* %0), !dbg !33
```

Any ideas?

Kind of suspecting a bug, but not sure yet. :wink:

**Comment by dannypsnl** [comment] 2019-06-08 05:21
Just check both can be compiled by my `clang`

#### clang version
```
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
```

Then I check the code, I think the problem is:
```
func (p *Param) String() string {
    return fmt.Sprintf("%s %s", p.Type(), p.Ident())
}
```
only return `i8* %0` part, so the problem might be do we want to bring nonnull information for `*ir.Param` with this attribute automatically, or we want to add this ability on to `value.Value` interface since it's an information for optimized I think.

From [reference](https://llvm.org/docs/LangRef.html)
> nonnull
This indicates that the parameter or return pointer is not null. This attribute may only be applied to pointer typed parameters. This is not checked or enforced by LLVM; if the parameter or return pointer is null, the behavior is undefined.

**Comment by mewmew** [comment] 2019-06-08 07:06
> Kind of suspecting a bug, but not sure yet. wink

I think you are right, this indeed looks like a bug. And as @dannypsnl pointed out, the bug is in `ir.Param.String`.

@justinclift, do you wanna take a stab at fixing it? :) If not, no worries. Could be a good first PR though (actual second, since you fixed the typo in #84 ^^)!

**Comment by justinclift** [comment] 2019-06-08 07:12
Hmmm, I'll take a look later on.  Kind of focused on my own bit atm. :wink:

**Comment by mewmew** [comment] 2019-06-08 07:21
> Hmmm, I'll take a look later on. Kind of focused on my own bit atm. wink

No rush :)

And, Happy hacking!

**Comment by mewmew** [comment] 2019-09-04 10:23
@justinclift, I think it should be possible to emit the `nonnull` parameter attribute for arguments of call instructions. I tried again today with fresh eyes and it should be possible to use [ir.NewArg]() for this purpose. See example code below (which is adapted from @dannypsnl example code in https://github.com/llir/llvm/pull/90#issuecomment-502342991).

```go
package main

import (
	"fmt"

	"github.com/llir/llvm/ir"
	"github.com/llir/llvm/ir/constant"
	"github.com/llir/llvm/ir/enum"
	"github.com/llir/llvm/ir/types"
)

func main() {
	m := ir.NewModule()
	f := m.NewFunc("main", types.I32)
	block := f.NewBlock("")
	alloc0 := block.NewAlloca(types.I8)
	bc0 := block.NewBitCast(alloc0, types.I8Ptr)
	bc0.LocalName = "stackalloc"
	load0 := block.NewLoad(bc0)

	p1 := ir.NewParam("", types.I8)
	p2 := ir.NewParam("", types.NewPointer(types.I8))
	p2.Attrs = []ir.ParamAttribute{
		enum.ParamAttrNonNull,
	}
	resourceWrite := m.NewFunc("resource_write", types.Void,
		p1,
		p2,
	)
	entry := resourceWrite.NewBlock("")
	entry.NewRet(nil)

	// Note, we use NewArg (not NewParam) for arguments to the call instruction.
	arg0 := ir.NewArg(bc0, enum.ParamAttrNonNull)
	block.NewCall(resourceWrite, load0, arg0)
	block.NewRet(constant.NewInt(types.I32, 0))
	fmt.Println(m)
}
```

Output
```llvm
define i32 @main() {
; <label>:0
	%1 = alloca i8
	%stackalloc = bitcast i8* %1 to i8*
	%2 = load i8, i8* %stackalloc
	call void @resource_write(i8 %2, i8* nonnull %stackalloc)
	ret i32 0
}

define void @resource_write(i8, i8* nonnull) {
; <label>:2
	ret void
}
```

@justinclift Let me know if this work out for you.

And thanks to both of you for helping trouble shoot this issue.

Cheers,
Robin

**Comment by mewmew** [comment] 2019-09-04 10:33
@justinclift 

re: your earlier example, it should be possible just to replace `NewParam` with `NewArg`, e.g.:

```diff
-foo := ir.NewParam("", types.I8Ptr)
-foo.Attrs = []ir.ParamAttribute{enum.ParamAttrNonNull}
+foo := ir.NewArg(valueToPass, enum.ParamAttrNonNull)
 someCall := ifThenIBlock.NewCall(val8, foo)  // val8() is already defined in earlier code
 someCall.Tail = enum.TailTail
 someCall.CallingConv = enum.CallingConvFast
 someCall.Metadata = append(someCall.Metadata, &metadata.Attachment{Name: "dbg", Node: dbgLoc["33"]})
```

where `valueToPass` is whatever value you have for `%0`, so for instance

```go
valueToPass := block.NewAlloca(types.I8)
```

**Comment by mewmew** [comment] 2019-09-05 20:24
Seeing as this issue is resolved, by using `ir.NewArg` for arguments to call instructions, I'll close the issue and @dannypsnl associated PR.

@justinclift if indeed the example in https://github.com/llir/llvm/issues/88#issuecomment-527840534 does not cover your use case, and you feel that it is not possible to produce an LLVM IR output that should be possible to produce, please re-open this issue (or a new one). I'd be glad to hear about such cases.

Cheers,
Robin

**Closed by mewmew** 2019-09-05 20:24 UTC
Labels: API

**Comment by justinclift** [comment] 2019-09-05 21:02
No worries @mewmew.  New job and related things recently, so haven't touched Go at all in a while.  :frowning:

**Comment by mewmew** [comment] 2019-09-06 06:32
> No worries @mewmew. New job and related things recently, so haven't touched Go at all in a while. frowning

That's fair. You are always welcome back when you feel like :)
