### ISSUE TITLE
align N may not work in call instruction

### ISSUE THREAD

**Issue by jeshan** [llir/llvm#198] opened 2021-07-21 17:43 UTC
I'm getting a parser error at the line below. Just removing "align 8" allows parsing to proceed

does not work:
```
  %15 = call nonnull align 8 dereferenceable(128) %"struct.llvm::ExecutionContext"* @_ZNSt6vectorIN4llvm16ExecutionContextESaIS1_EE4backEv(%"class.std::vector.40"* %14) #2, !dbg !29564
```

works:
```
  %15 = call nonnull dereferenceable(128) %"struct.llvm::ExecutionContext"* @_ZNSt6vectorIN4llvm16ExecutionContextESaIS1_EE4backEv(%"class.std::vector.40"* %14) #2, !dbg !29564
```

This was obtained as part of a larger compilation context with

`Ubuntu clang version 11.0.0-2~ubuntu20.04.1`

tested with this in my go.mod:

`github.com/llir/llvm v0.3.4-0.20210604083140-7e6606e193a1`

Note that I checked the [reference for LLVM 11](https://releases.llvm.org/11.0.0/docs/LangRef.html#call-instruction) but it's unclear that "align N" is supposed to be valid. I only saw "align N" and "dereferenceable N" documented for parameter attributes (but my compilation process worked totally fine)

Let me know what else I should provide.

**Comment by mewmew** [comment] 2021-07-22 13:46
This is probably related to #40. There are parsing ambiguities of the grammar related to alignment directives (see #40 for further background).

From [ll.tm](https://github.com/llir/grammar/blob/5291534192d972964c2745b7c18ac47208dc6be5/ll.tm#L2753):
```python
# TODO: add align as valid function attribute to CallInst.

CallInst -> CallInst
```

Similarly for return attributes,

```python
ReturnAttribute -> ReturnAttribute
	# TODO: Figure out how to re-enable without getting these errors in FuncHeader:
	#    - two unnamed fields share the same type `AttrPair`: ReturnAttribute -vs- FuncAttribute
	#    - `AttrPair` occurs in both named and unnamed fields
	#    - `ReturnAttrs` cannot be nullable, since it precedes FuncAttrs
	#: AttrString
	#| AttrPair
	#| Align
```

I don't know a good way to solve #40. If you find any, please let me know :)

**Comment by mewmew** [comment] 2021-07-31 09:53
Closing as duplicate of #40. If it turns out this is not a duplicate, please feel free to re-open this issue.

Cheers,
Robin

**Closed by mewmew** 2021-07-31 09:53 UTC
Labels: duplicate, grammar
