### ISSUE TITLE
Help: Calling a function multiple times doesn't work

### ISSUE THREAD

**Issue by Nv7-GitHub** [llir/llvm#179] opened 2021-05-17 05:15 UTC
Is this the right place to ask for help?

Anyway, calling `printf` once works:
```ll
@tmp0 = global [14 x i8] c"Hello, World!\0A"

define i32 @main() {
0:
	%1 = getelementptr [14 x i8], [14 x i8]* @tmp0, i64 0, i64 0
	%2 = call i32 (i8*, ...) @printf(i8* %1)
	ret i32 0
}

declare i32 @printf(i8* %0, ...)
```
Output:
```
Hello, World!
```

But calling `printf` a second time results in it being called twice, once with invalid args.
```ll
@tmp0 = global [14 x i8] c"Hello, World!\0A"
@tmp1 = global [13 x i8] c"1 + 2 is: %d\0A"

define i32 @main() {
0:
	%1 = getelementptr [14 x i8], [14 x i8]* @tmp0, i64 0, i64 0
	%2 = call i32 (i8*, ...) @printf(i8* %1)
	%3 = getelementptr [13 x i8], [13 x i8]* @tmp1, i64 0, i64 0
	%4 = add i32 1, 2
	%5 = call i32 (i8*, ...) @printf(i8* %3, i32 %4)
	ret i32 0
}

declare i32 @printf(i8* %0, ...)
```

Output:
```
Hello, World!
1 + 2 is: -390642568
1 + 2 is: 3
```

When I call it a 3rd time, it prints three times:
```ll
@tmp0 = global [14 x i8] c"Hello, World!\0A"
@tmp1 = global [13 x i8] c"1 + 2 is: %d\0A"
@tmp2 = global [15 x i8] c"0.1 + 2 is: %f\0A"

define i32 @main() {
0:
	%1 = getelementptr [14 x i8], [14 x i8]* @tmp0, i64 0, i64 0
	%2 = call i32 (i8*, ...) @printf(i8* %1)
	%3 = getelementptr [13 x i8], [13 x i8]* @tmp1, i64 0, i64 0
	%4 = add i32 1, 2
	%5 = call i32 (i8*, ...) @printf(i8* %3, i32 %4)
	%6 = sitofp i32 2 to double
	%7 = getelementptr [15 x i8], [15 x i8]* @tmp2, i64 0, i64 0
	%8 = fadd double 0x3FB999999999999A, %6
	%9 = call i32 (i8*, ...) @printf(i8* %7, double %8)
	ret i32 0
}

declare i32 @printf(i8* %0, ...)
```

Output:
```
Hello, World!
1 + 2 is: -452680584
0.1 + 2 is: 0.000000
1 + 2 is: 3
0.1 + 2 is: 0.000000
0.1 + 2 is: 2.100000
```

 Also, it isn't an issue with the math or integer printing or float printing. This is what happens when I call the math one once:
```ll
@tmp0 = global [13 x i8] c"1 + 2 is: %d\0A"

define i32 @main() {
0:
	%1 = getelementptr [13 x i8], [13 x i8]* @tmp0, i64 0, i64 0
	%2 = add i32 1, 2
	%3 = call i32 (i8*, ...) @printf(i8* %1, i32 %2)
	ret i32 0
}

declare i32 @printf(i8* %0, ...)
```

Output:
```
1 + 2 is: 3
```

When I call only the integer math one and then the float math one, it calls the integer math one once (working) and the float math one twice.

**Comment by mewmew** [comment] 2021-05-17 08:52
Hi @Nv7-GitHub,

I think this is caused by missing NULL-byte in the strings.

```diff
--- orig.ll	2021-05-17 10:53:14.750089233 +0200
+++ new.ll	2021-05-17 10:52:44.886755490 +0200
@@ -1,11 +1,11 @@
-@tmp0 = global [14 x i8] c"Hello, World!\0A"
-@tmp1 = global [13 x i8] c"1 + 2 is: %d\0A"
+@tmp0 = global [15 x i8] c"Hello, World!\0A\00"
+@tmp1 = global [14 x i8] c"1 + 2 is: %d\0A\00"
 
 define i32 @main() {
 0:
-	%1 = getelementptr [14 x i8], [14 x i8]* @tmp0, i64 0, i64 0
+	%1 = getelementptr [15 x i8], [15 x i8]* @tmp0, i64 0, i64 0
 	%2 = call i32 (i8*, ...) @printf(i8* %1)
-	%3 = getelementptr [13 x i8], [13 x i8]* @tmp1, i64 0, i64 0
+	%3 = getelementptr [14 x i8], [14 x i8]* @tmp1, i64 0, i64 0
 	%4 = add i32 1, 2
 	%5 = call i32 (i8*, ...) @printf(i8* %3, i32 %4)
 	ret i32 0
```

Output after fix:

```
Hello, World!
1 + 2 is: 3
```

Closing this issue as resolved. Let us know if it is not working.

Cheers,
Robin

**Closed by mewmew** 2021-05-17 08:52 UTC
