### ISSUE TITLE
ir: rename NewFunction to NewFunc 

### ISSUE THREAD

**Issue by pwaller** [llir/llvm#44] opened 2018-11-25 21:39 UTC
Just want to question a4f2487113c4b857d47dcd1f3851f7a91faa99e7. Is there a good rationale for it? One rule I try to abide by is "only have one name for a thing, to the extent it is possible". So it should be `type Func` xor `func NewFunction`.

**Comment by mewmew** [comment] 2018-11-25 21:44
> Just want to question a4f2487. Is there a good rationale for it? One rule I try to abide by is "only have one name for a thing, to the extent it is possible". So it should be type Func xor func NewFunction.

I'd say it's a good rule in general. The reason really is that we will end up typing ir.NewFunc quite often, and thus making it shorter makes it more pleasant to use. This is analogous to the `func` keyword in Go.

As for having the same name for the type as the construction, sure. We already have another case where the constructor is an abbreviated version of the type name, [ir.NewBlock](https://godoc.org/github.com/llir/llvm/ir#NewBlock) returning [*ir.BasicBlock](https://godoc.org/github.com/llir/llvm/ir#BasicBlock).

There are also two constructors where the name does not match, but that is by design. [ir.NewGlobalDecl](https://godoc.org/github.com/llir/llvm/ir#NewGlobalDecl) and [ir.NewGlobalDef](https://godoc.org/github.com/llir/llvm/ir#NewGlobalDef) both return [*ir.Global](https://godoc.org/github.com/llir/llvm/ir#Global).

**Comment by mewmew** [comment] 2018-12-30 13:01
I think I'm starting to lean more towards your suggestion, to make consistent use of one name throughout. I'd therefore like to get this in place before tagging the final v0.3 release.

The two primary API changes are as follows:
* rename `type Function` to `type Func`
* rename `type BasicBlock` to `type Block`

If we find any other inconsistent use of naming, lets add it to this issue.

**Comment by mewmew** [comment] 2018-12-30 13:37
I think we can close this issue as the constructor and type names are now consistent. If we find any others, we can simply re-open it later. Thanks for reporting it @pwaller!

**Closed by mewmew** 2018-12-30 13:37 UTC
